# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://114.132.155.68:3306/user_center?useSSL=false'
    username: root
    password: feifan66!
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
